// Represents an image associated with a collocation offer
export interface CollocationImage {
  id?: number;
  fileName?: string;
  filePath?: string;
  // Add other fields that come from the backend (e.g., createdAt)
}

// Main offer model
export interface CollocationOffer {
  id?: number;                 // Generated by backend, optional when creating
  titre: string;                // Maps to backend 'titre'
  description: string;
  prixLoc: number;              // Maps to backend 'prixLoc'
  ville: string;                // Maps to backend 'ville'
  chambres: number;             // Number of rooms
  meublee: boolean;             // Furnished or not
  latitude?: number;            // Optional, might be set later
  longitude?: number;           // Optional
  createdAt?: Date;             // Usually set by backend
  expiryDate?: Date;            // Optional, maybe calculated
  ownerId?: number;             // ID of the user who created it
  imagesColoc?: CollocationImage[];  // Array of associated images
}
